name: Run Python script every 5 minutes

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium schedule

    - name: Run script
      run: python main.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pizza_places
        path: ./*.csv
