name: Run Python script every 5 minutes and commit results to repo

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run script
      run: python main.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes if there are any
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git add results/*.csv
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Add generated CSV files to results folder"
          git push -u origin HEAD:main
        else
          echo "No changes to commit"
